-- Locations
CREATE SEQUENCE TIMES_SERVICE.SEQ_TS_LOCATIONS
    INCREMENT 1
    START 1;

ALTER SEQUENCE TIMES_SERVICE.SEQ_TS_LOCATIONS
    OWNED BY TIMES_SERVICE.TS_LOCATIONS.ID;

ALTER SEQUENCE TIMES_SERVICE.SEQ_TS_LOCATIONS
    OWNER TO postgres;